### ISSUE TITLE
Implement ontofetch configuration file and `update` command

### ISSUE THREAD

**Issue by jamesaoverton** [knocean/ontofetch#21]
We should implement a `ontofetch.yaml` file that configures projects and how they should be fetched. Draft example:

```
projects:
  - project: obi
    directory: YYYY-MM-DD
    url: http://purl.obolibrary.org/obo/obi.owl
    frequency: 24h
```

When we call `ontofetch run` it should:

1. read the configuration file
2. look somewhere (the catalog?) for a timestamp of the last call to `ontofetch run`
3. for each project
    - if the last run was longer ago than the `frequency`, fill in the `directory` and fetch the URL
    - otherwise report 
4. report text on the command line
5. generate an HTML report

`ontofetch run` should support:

- specifying one or more projects to run; the default is to run all of them
- ` --force` option that will ignore the last update time
